[package]
name = "vulkan-playground"
version = "0.1.0"
authors = ["Arne Vansteenkiste <barnex@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
winit = "0.22"
vulkano-win = "0.19.0"
